### ISSUE TITLE
💡 [REQUEST] - Add IPA file to downloads

### ISSUE THREAD

**Issue by krinkuto11** [Fladder-App/Fladder#21]
### Summary

Title is self descriptive, add an IPA workflow so it is available for download with each release.

### Basic Example

This medium [page](https://medium.com/@colonal/automating-flutter-builds-and-releases-with-github-actions-77ccf4a1ccdd) describes a way to accomplish this

### Drawbacks

None as far I am concerned.

**Comment by bazzadazza72** [comment]
We're in the process of doing that. Currently, the action is failing to package the IPA, complaining with a `No Team Found in Archive` error. I haven't got a macOS environment to attempt a build, but if you have some experience with iOS, any contribution is appreciated.

**Comment by krinkuto11** [comment]
That's weird, I forked the `develop` branch and ran the action (for version 0.2.4), which resulted in a succesful IPA being generated but failed at doing so with Android APK and Linux. Anyways, I do own a Mac so I will try to look at it.

**Comment by bazzadazza72** [comment]
Thanks a lot. I was compiling my builds on my fork too, so I figured it was due to not having any secrets or environment variables set.

Out of curiosity, did you try doing a run on your own fork, with the latest workflow file? I submitted a PR (specifically #16) which should have fixed Linux building.

**Comment by krinkuto11** [comment]
Yes, I ran it in my own fork. I forked the repo 14h ago and it says that it's up to date so I must be using the latest workflow file.

**Linux** build shows this error ` Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
`

**Android** build shows this one ` [!] Your project requires a newer version of the Kotlin Gradle plugin. Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  version number of the plugin with id "org.jetbrains.kotlin.android" in the plugins block of /home/runner/work/Fladder/Fladder/android/settings.gradle.
Alternatively (if your project was created before Flutter 3.19), update /home/runner/work/Fladder/Fladder/android/build.gradle 
ext.kotlin_version = '<latest-version>'    `

**Comment by bazzadazza72** [comment]
Just submitted a PR to fix the Linux issue, there was some confusion when I was syncing my fork and the update was reverted (#24). I'll get a PR set up to update the Gradle plugin when I've got time.

Thanks for your help, we're getting there!

**Comment by PartyDonut** [comment]
Hey all, sorry for the late response.
Yes ipa should work now I just had not gotten around yet to uploading the artifacts. I will test run the linux build as well, so all builds should be working.

**Comment by PartyDonut** [comment]
Version [0.2.5-alpha](https://github.com/Fladder-App/Fladder/releases/tag/v0.2.5) has all builds included in the assets tab.

**Comment by PartyDonut** [comment]
Thanks for reporting back thats great to hear 👍🏼.

Can you create issues for those bugs?

**Comment by p0358** [comment]
Opened in #26 #27
